### ISSUE TITLE
master节点管理中,启动重复节点,导致原有正常节点失效

### ISSUE THREAD

**Issue by zllangct** [viphxin/xingo#10]
当已经启动过一个节点的时候,因为失误或者其他原因重复启动某一节点时,原有正常的的节点会失效.正确的姿势应该是提示该节点已经启动. master rpc中的TakeProxy应该做相应处理.....这个对运营至关重要

**Comment by viphxin** [comment]
这个Issue其实和节点平滑升级那个Issue有点关联，比如原有节点异常需要用新节点替换，那这种直接替换原节点接管原节点请求的方式就应该算很方便了，不过这可能不是最优雅的方式。最优雅的节点平滑升级的方式可能基于具体的业务场景来设计更好一些。最后还是强烈安利xingo telnet工具，大部分xingo没有的功能都可以通过xingo telnet工具补充
