### ISSUE TITLE
关于节点平滑升级的请教

### ISSUE THREAD

**Issue by zllangct** [viphxin/xingo#11]
纯golang要做到热更新,感觉目前还没有很成熟的一套东西,做到平滑升级还是可行的.当某一节点的新版本启动时,停止向旧节点发起服务请求,新的服务全部转向新节点,等待旧节点完成所有服务后关闭.在xingo现有的构架上面实现并不算很难,希望作者大大考虑一下.

**Comment by viphxin** [comment]
非常感谢你的建议，节点平滑升级对于大部分服务来说都是很有意义。xingo目前的版本计划有：性能优化，集群管理自动化等，节点平滑升级其实也包含在集群管理自动化里面。当然基于当前的xingo版本要实现节点平滑升级也是相当简单的事情，比如方案1可以利用xingo telnet工具在节点中实现gm命令，通过gm指令来上线／下线节点
