### ISSUE TITLE
学习下，为什么这边不直接 net.Listen(network, address)

### ISSUE THREAD

**Issue by ruandao** [viphxin/xingo#15]
https://github.com/viphxin/xingo/blob/bfb5c6f1ee6b57bd04cb9de22c0a7e18c73d35b0/fserver/server.go#L85-L90

ln, err := net.Listen(this.IPVersion, fmt.Sprintf("%s:%d", this.IP, this.Port))

这样写，有什么好处？

谢谢

**Comment by viphxin** [comment]
效果是差不多的，个人习惯吧
