### ISSUE TITLE
gob不注册类型没有报错吗

### ISSUE THREAD

**Issue by tobygz** [viphxin/xingo#4]
gob.Register(RpcData{})
gob.Register([]interface{}{})

我加了以上两句。。。不然会报错类型不支持

**Comment by viphxin** [comment]
不需要像以上那样注册，只有当需要gob序列化的结构体中有interface{}类型的字段并且interface{}的可能类型为非内置类型时才需要gob.Register；xingo本身默认rpc调用的参数和返回结构都是基本类型；当然参数和返回结果也可以是开发者自定义类型，这个时候才需要开发者自己去注册具体的类型，xingo本身预期不了开发者在使用过程中会自定义哪些类型。
