### ISSUE TITLE
我是一楼， 作者你好，这个是不是仿pomelo的

### ISSUE THREAD

**Issue by ghost** [viphxin/xingo#8]
作者你好，这个是不是仿pomelo的，对这个很感兴趣，可惜文档太少

**Comment by viphxin** [comment]
感谢你的关注，xingo没有仿pomelo，可能服务器架构中的很多思想是相近的，看起来有pomelo的影子。。最后文档会持续完善的，希望能持续关注，多提意见。

**Comment by ghost** [comment]
好的呀
